const generatePDF = require("./pdfService");
const nodemailer = require("nodemailer");

const sendAuditEmail = async (
  email,
  companyName,
  scrapedData,
  insights
) => {
  try {
    const pdfPath = await generatePDF(
    companyName,
    scrapedData,
    insights
    );
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    await transporter.sendMail({
    from: process.env.EMAIL_USER,
    to: email,
    subject: `AI Audit Report for ${companyName}`,

    html: `
        <h1>SimplifiIQ AI Audit Report</h1>

        <h2>Company</h2>
        <p>${companyName}</p>

        <h2>Website Title</h2>
        <p>${scrapedData.title}</p>

        <h2>Meta Description</h2>
        <p>${scrapedData.metaDescription}</p>

        <h2>AI Insights</h2>

        <pre style="white-space: pre-wrap; font-family: sans-serif;">
    ${insights}
        </pre>

        <br/>

        <p>Generated by SimplifiIQ AI Platform</p>
    `,

    attachments: [
        {
        filename: `${companyName}-report.pdf`,
        path: pdfPath,
        },
    ],
    });

    console.log("Email sent successfully");
  } catch (error) {
    console.log("Email failed:", error);
  }
};

module.exports = sendAuditEmail;